[project]
name = "bedit-backend"
version = "0.1.1"
description = "Default template for PDM package"
authors = [
    { name = "thoulee", email = "thou_lee@outlook.com" },
]
dependencies = [
    "erniebot>=0.5.7",
    "flask[async]>=3.0.3",
    "loguru>=0.7.2",
    "flask-cors>=4.0.1",
    "markdown>=3.6",
    "rpds-py>=0.18.1",
    "uwsgi>=2.0.26",
]
requires-python = ">=3.10.*"
readme = "README.md"
license = { text = "MIT" }


[tool.pdm]
distribution = false

[tool.pdm.scripts]
server = "python ./src/bedit_backend/server.py"
