[project]
name = "bedit-backend"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "thoulee", email = "thou_lee@outlook.com"},
]
dependencies = [
    "erniebot>=0.5.7",
    "flask>=3.0.3",
    "markdown>=3.6",
    "user-agents>=2.2.0",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
