# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
 
name: Flask API Deploy
 
on:
  push:
    branches: [ deploy ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:   #  参考：https://github.com/marketplace/actions/ssh-remote-commands
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
        PORT: ${{ secrets.PORT }}
        script: |           # 这里根据自己项目写自己实际需要执行的脚本，其实就是pull代码启动server
          cd /root/repos/bedit-backend/src/bedit_backend
          git pull
          git co deploy
          pdm install
          systemctl restart uwsgi.service